# Generated by Django 5.2.1 on 2025-07-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promedio_strip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_studio', models.IntegerField()),
                ('promedio', models.FloatField()),
                ('contador', models.IntegerField()),
                ('users', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'promedio_strip',
                'managed': False,
            },
        ),
    ]
