services:
  - type: web
    name: libog-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn sistema_login.wsgi:application"
    region: oregon  # Puedes cambiar la región si estás en otro país
    plan: free