

#services:
#  - type: web
#    name: libog-django
#    env: python
#    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
#    startCommand: "gunicorn sistema_login.wsgi:application"
#    region: oregon
#    plan: free
#    build:
#      environment:
#        PYTHON_VERSION: 3.11

services:
  - type: web
    name: libog-django
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn sistema_login.wsgi:application"
    region: oregon
    plan: free

  - type: cron
    name: libog-cronjob
    env: python
    schedule: "*/3 * * * *"  # Cada 5 minutos
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python cron_jobs/mi_script.py"
    plan: starter  # Esto ya es de pago (por minutos)
