#services:
#  - type: web
#    name: libog-django
#    env: python
#    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
#    startCommand: "gunicorn sistema_login.wsgi:application"
#    region: oregon  # Puedes cambiar la región si estás en otro país
#    plan: free

services:
  - type: web
    name: libog-django
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn sistema_login.wsgi:application"
    region: oregon
    plan: free
    build:
      environment:
        PYTHON_VERSION: 3.11
