# Generated by Django 5.2.1 on 2025-06-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoStudio',
            fields=[
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('id_studio', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'info_users',
                'managed': False,
            },
        ),
    ]
