# Generated by Django 5.2.1 on 2025-05-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='infostudio',
            table='info_users',
        ),
    ]
