# Generated by Django 5.2.1 on 2025-06-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tokens_cb', models.PositiveIntegerField(default=0)),
                ('tokens_otro', models.PositiveIntegerField(default=0)),
                ('promedio_sala', models.FloatField(blank=True, null=True)),
                ('promedio_users', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promedio',
                'managed': False,
            },
        ),
    ]
