# Generated by Django 5.2.1 on 2025-06-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos_tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingresotokens',
            table='ingreso_token',
        ),
    ]
