"""
Django settings for sistema_login project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%1c%m4trx27i0b&m@-hf992ie0l(bl*xl*p(3c0hybt7ae+sa2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['libog-django.onrender.com','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'modelos_app',
    'posicion',
    'promedio',
    'monitores',
    'ingresos_tokens',
    'posicion_strip',    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_login.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_login.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': 'ba69cotht6ptecop3sey',        # 👈 Cambia esto
    #    'USER': 'uec39ms83p7pwccc',         # 👈 Cambia esto
    #    'PASSWORD': 'gPDkaLJoBbQcrDD5xaLe',  # 👈 Cambia esto
    #    'HOST': 'ba69cotht6ptecop3sey-mysql.services.clever-cloud.com',                # o IP del servidor MySQL
    #    'PORT': '3306',                     # puerto por defecto de MySQL
    #    'CONN_MAX_AGE': 60,  # o 300, según tu necesidad
    #}
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'libog_data',        # 👈 Cambia esto
        'USER': 'doadmin',         # 👈 Cambia esto
        'PASSWORD': 'AVNS_sSHHxLG4_1wcJeWyrYe',  # 👈 Cambia esto
        'HOST': 'libog-mysql-do-user-23452643-0.d.db.ondigitalocean.com',                # o IP del servidor MySQL
        'PORT': '25060',                     # puerto por defecto de MySQL
        'CONN_MAX_AGE': 60,  # o 300, según tu necesidad
        'OPTIONS': {
            'ssl': {
                'ca': config('SSL_CA_PATH', default='certs/ca-certificate.crt')
            }
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

#cierra sesion al cerrar navegador
# Duración máxima de la sesión sin actividad (en segundos)
SESSION_COOKIE_AGE = 1800  # 1800 segundos = 30 minutos

# Opcional: cerrar sesión al cerrar el navegador también
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# (Opcional, más estricto) Hace que el contador se reinicie solo si hay una nueva solicitud
SESSION_SAVE_EVERY_REQUEST = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Carpeta con tus archivos estáticos
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Carpeta donde Django los copiará para producción


TIME_ZONE = 'America/Bogota'
USE_TZ = True


CRON_TOKEN = "qwertyPANAMA9876"

