# Generated by Django 5.2.1 on 2025-05-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posicion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='informacion',
        ),
    ]
