# Generated by Django 5.2.1 on 2025-05-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelos_app', '0002_rename_fecha_registro_modeloregistrado_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_studio', models.IntegerField(db_column='id_studio')),
                ('promedio', models.FloatField()),
                ('contador', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.CASCADE, to='modelos_app.modeloregistrado')),
            ],
            options={
                'db_table': 'promedio',
            },
        ),
    ]
