# Generated by Django 5.2.1 on 2025-05-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promedio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promedio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
