# Generated by Django 5.2.1 on 2025-05-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promedio', '0002_alter_promedio_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promedio',
            options={'managed': False},
        ),
    ]
