# Generated by Django 5.2.1 on 2025-06-26 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(default=1)),
                ('id_monitor', models.IntegerField(default=0)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.infostudio')),
            ],
            options={
                'db_table': 'data_models',
                'constraints': [models.UniqueConstraint(fields=('studio', 'usuario'), name='unique_usuario_por_studio')],
            },
        ),
    ]
