# Generated by Django 5.2.1 on 2025-07-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos_app', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modeloregistrado',
            name='unique_usuario_por_studio',
        ),
        migrations.AddField(
            model_name='modeloregistrado',
            name='usuario_strip',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='modeloregistrado',
            constraint=models.UniqueConstraint(fields=('studio', 'usuario', 'usuario_strip'), name='unique_usuario_por_studio'),
        ),
    ]
