# Generated by Django 5.2.1 on 2025-05-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos_app', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeloregistrado',
            old_name='fecha_registro',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='modeloregistrado',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modeloregistrado',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='modeloregistrado',
            constraint=models.UniqueConstraint(fields=('studio', 'usuario'), name='unique_usuario_por_studio'),
        ),
        migrations.AlterModelTable(
            name='modeloregistrado',
            table='informacion',
        ),
    ]
