# Generated by Django 5.2.1 on 2025-06-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos_app', '0001_initial'),
        ('usuarios', '0002_alter_infostudio_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modeloregistrado',
            name='unique_usuario_por_studio',
        ),
        migrations.RenameField(
            model_name='modeloregistrado',
            old_name='studio',
            new_name='id_studio',
        ),
        migrations.AddConstraint(
            model_name='modeloregistrado',
            constraint=models.UniqueConstraint(fields=('id_studio', 'usuario'), name='unique_usuario_por_studio'),
        ),
    ]
