# Generated by Django 5.2.1 on 2025-06-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos_app', '0003_remove_modeloregistrado_unique_usuario_por_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloregistrado',
            name='monitor',
            field=models.IntegerField(default=0),
        ),
    ]
