# Generated by Django 5.2.1 on 2025-06-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos_app', '0004_modeloregistrado_monitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeloregistrado',
            old_name='monitor',
            new_name='id_monitor',
        ),
    ]
