name: Ejecutar guardar_promedios

on:
  schedule:
    - cron: '*/3 * * * *'  # Cada 5 minutos (en horario UTC)
  workflow_dispatch:  # Permite correrlo manualmente también

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Cambia si usas otra versión

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar comando
      run: |
        python manage.py guardar_promedios
